version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/RubyReactBlog"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
