version: "3.9"
services:
  web:
    build:
      target: build
    command: bundle exec rails server -b 0.0.0.0
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      VITE_RUBY_HOST: "0.0.0.0"
    # volumeが上書きされて挙動がおかしいのでコメントアウト
    # volumes:
    #   - ".:/RubyReactBlog"
    #   - node_modules:/RubyReactBlog/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  vite:
    build:
      target: build
    command: bin/vite dev
    ports:
      - "3036:3036"
    depends_on:
      - web

volumes:
  node_modules:
